'use strict';
const EventBus = require('../../core/EventBus');
const SystemDB = require('../../database/SystemDB');
const SocketBridge = require('../../core/SocketBridge');
const AIEngine = require('./AIEngine');
let timer = null; let workerBusy = false;
const ALLOWED_TRANSITIONS = { queued:['running','blocked','cancelled'], running:['success','failed','retrying','waiting_approval'], retrying:['running','failed'], waiting_approval:['queued','cancelled'], paused:['queued','cancelled'] };
const TOOLS = [
  { name:'search', label:'Search Tool', risk:'low', description:'قراءة نتائج البحث المسموح بها' },
  { name:'database_read', label:'Database Read', risk:'low', description:'قراءة بيانات النطاق الحالي' },
  { name:'group_read', label:'Group Tool', risk:'medium', description:'قراءة المجموعات المتاحة للحساب' },
  { name:'keyword_read', label:'Keyword Tool', risk:'low', description:'قراءة تطابقات الكلمات المفتاحية' },
  { name:'statistics', label:'Statistics Tool', risk:'low', description:'قراءة الإحصائيات' },
  { name:'notification', label:'Notification Tool', risk:'medium', description:'إرسال تنبيه داخل اللوحة' },
  { name:'workflow_trigger', label:'Workflow Tool', risk:'high', description:'تشغيل Workflow آخر بعد التحقق' },
];
function userId(req){return req.user?.id||req.user?.userId;}
async function emit(event,payload){try{SocketBridge.to(`user:${payload.userId}`).emit(event,payload);}catch{}}
async function audit(userId, action, details={}, refs={}){await SystemDB.run(`INSERT INTO ai_audit_log(user_id,task_id,workflow_id,agent_id,action,details) VALUES($1,$2,$3,$4,$5,$6)`,[userId,refs.task_id||null,refs.workflow_id||null,refs.agent_id||null,action,JSON.stringify(details)]);}
async function stats(userId){
  const tasks=await SystemDB.get(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='running')::int active,COUNT(*) FILTER(WHERE status='queued')::int queued,COUNT(*) FILTER(WHERE status='success')::int completed,COUNT(*) FILTER(WHERE status='failed')::int failed,COUNT(*) FILTER(WHERE status='waiting_approval')::int approvals FROM ai_tasks WHERE user_id=$1`,[userId]);
  const workflows=await SystemDB.get(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='active')::int active FROM ai_workflows WHERE user_id=$1`,[userId]);
  const agents=await SystemDB.get(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='active')::int active FROM ai_agents WHERE user_id=$1`,[userId]);
  const events=await SystemDB.get(`SELECT COUNT(*)::int total FROM ai_events WHERE user_id=$1`,[userId]); const alerts=await SystemDB.get(`SELECT COUNT(*)::int open FROM ai_alerts WHERE user_id=$1 AND status='open'`,[userId]);
  const provider=process.env.AI_PROVIDER||'none'; return { tasks, workflows, agents, events:Number(events?.total||0), alerts:Number(alerts?.open||0), ai_provider:provider, ai_online:provider!=='none' && Boolean(process.env.OPENAI_API_KEY||process.env.ANTHROPIC_API_KEY), automation_online:Boolean(timer) };
}
const service={
  tools:()=>TOOLS,
  getUserId:userId,
  async dashboard(uid){const s=await stats(uid);const [recent,errors,approvals]=await Promise.all([SystemDB.all(`SELECT id,name,status,task_type,created_at,updated_at FROM ai_tasks WHERE user_id=$1 ORDER BY created_at DESC LIMIT 12`,[uid]),SystemDB.all(`SELECT * FROM ai_alerts WHERE user_id=$1 ORDER BY created_at DESC LIMIT 12`,[uid]),SystemDB.all(`SELECT * FROM ai_approvals WHERE user_id=$1 AND status='pending' ORDER BY created_at DESC LIMIT 12`,[uid])]);return {stats:s,recent,errors,approvals,tools:TOOLS};},
  async agents(uid){return SystemDB.all(`SELECT * FROM ai_agents WHERE user_id=$1 ORDER BY created_at DESC`,[uid]);},
  async createAgent(uid,b){if(!b?.name)throw new Error('اسم الوكيل مطلوب');const row=await SystemDB.get(`INSERT INTO ai_agents(user_id,name,description,goal,instructions,model,autonomy,tools,memory,guardrails,max_steps,timeout_seconds,retry_limit,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'paused') RETURNING *`,[uid,b.name,b.description||'',b.goal||'',b.instructions||'',b.model||process.env.AI_MODEL||'default',b.autonomy||'supervised',JSON.stringify(b.tools||[]),JSON.stringify(b.memory||{}),JSON.stringify(b.guardrails||{}),Number(b.max_steps)||10,Number(b.timeout_seconds)||120,Number(b.retry_limit)||2]);await audit(uid,'agent.created',b,{agent_id:row.id});return row;},
  async toggleAgent(uid,id,status){const row=await SystemDB.get(`UPDATE ai_agents SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3 RETURNING *`,[status,id,uid]);if(!row)throw new Error('الوكيل غير موجود');await audit(uid,'agent.status_changed',{status},{agent_id:id});return row;},
  async workflows(uid){return SystemDB.all(`SELECT * FROM ai_workflows WHERE user_id=$1 ORDER BY updated_at DESC`,[uid]);},
  async createWorkflow(uid,b){if(!b?.name)throw new Error('اسم Workflow مطلوب');const row=await SystemDB.get(`INSERT INTO ai_workflows(user_id,name,description,trigger_type,nodes,status) VALUES($1,$2,$3,$4,$5,'draft') RETURNING *`,[uid,b.name,b.description||'',b.trigger_type||'manual',JSON.stringify(b.nodes||[])]);await audit(uid,'workflow.created',b,{workflow_id:row.id});return row;},
  async updateWorkflow(uid,id,b){const row=await SystemDB.get(`UPDATE ai_workflows SET name=COALESCE($1,name),description=COALESCE($2,description),trigger_type=COALESCE($3,trigger_type),nodes=COALESCE($4,nodes),version=version+1,updated_at=NOW() WHERE id=$5 AND user_id=$6 RETURNING *`,[b.name||null,b.description||null,b.trigger_type||null,b.nodes?JSON.stringify(b.nodes):null,id,uid]);if(!row)throw new Error('Workflow غير موجود');return row;},
  async toggleWorkflow(uid,id,status){const row=await SystemDB.get(`UPDATE ai_workflows SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3 RETURNING *`,[status,id,uid]);if(!row)throw new Error('Workflow غير موجود');await audit(uid,'workflow.status_changed',{status},{workflow_id:id});return row;},
  async tasks(uid,limit=50){return SystemDB.all(`SELECT * FROM ai_tasks WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2`,[uid,Math.min(100,Number(limit)||50)]);},
  async createTask(uid,b){if(!b?.name)throw new Error('اسم المهمة مطلوب');const risk=Math.max(0,Math.min(100,Number(b.risk_score)||0));const status=risk>=81?'blocked':risk>=51?'waiting_approval':'queued';const idem=b.idempotency_key||`${b.task_type||'manual'}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;let row;try{row=await SystemDB.get(`INSERT INTO ai_tasks(user_id,workflow_id,agent_id,name,task_type,payload,status,priority,risk_score,confidence,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING *`,[uid,b.workflow_id||null,b.agent_id||null,b.name,b.task_type||'manual',JSON.stringify(b.payload||{}),status,Number(b.priority)||5,risk,b.confidence==null?null:Number(b.confidence),idem]);}catch(e){throw new Error('تعذر إنشاء المهمة: '+e.message);}if(!row)throw new Error('المهمة موجودة مسبقاً ولم تُكرر');await audit(uid,'task.created',{status,risk_score:risk},{task_id:row.id,workflow_id:row.workflow_id,agent_id:row.agent_id});if(status==='waiting_approval'){await SystemDB.run(`INSERT INTO ai_approvals(user_id,task_id,reason,proposed_action,risk_score,confidence) VALUES($1,$2,$3,$4,$5,$6)`,[uid,row.id,'مستوى خطورة مرتفع ويتطلب موافقة بشرية',b.proposed_action||'مراجعة المهمة',risk,row.confidence]);}return row;},
  async controlTask(uid,id,action){const row=await SystemDB.get(`SELECT * FROM ai_tasks WHERE id=$1 AND user_id=$2`,[id,uid]);if(!row)throw new Error('المهمة غير موجودة');const map={cancelled:'cancelled',pause:'paused',resume:'queued',retry:'queued'};const next=map[action];if(!next)throw new Error('إجراء غير صالح');if(row.status==='waiting_approval'&&action==='resume')throw new Error('المهمة تنتظر موافقة بشرية');if(row.status==='cancelled'||row.status==='success')throw new Error('لا يمكن تغيير حالة المهمة الحالية');await SystemDB.run(`UPDATE ai_tasks SET status=$1,retry_count=CASE WHEN $1='queued' AND $2='retry' THEN retry_count+1 ELSE retry_count END,updated_at=NOW() WHERE id=$3 AND user_id=$4`,[next,action,id,uid]);await audit(uid,'task.status_changed',{action,next},{task_id:id});return SystemDB.get(`SELECT * FROM ai_tasks WHERE id=$1`,[id]);},
  async approvals(uid){return SystemDB.all(`SELECT a.*,t.name,t.task_type,t.payload FROM ai_approvals a JOIN ai_tasks t ON t.id=a.task_id WHERE a.user_id=$1 ORDER BY a.created_at DESC LIMIT 100`,[uid]);},
  async decideApproval(uid,id,decision,note){if(!['approved','rejected'].includes(decision))throw new Error('قرار غير صالح');const a=await SystemDB.get(`UPDATE ai_approvals SET status=$1,decision_by=$2,decision_note=$3,decided_at=NOW() WHERE id=$4 AND user_id=$5 AND status='pending' RETURNING *`,[decision,uid,note||'',id,uid]);if(!a)throw new Error('طلب الموافقة غير موجود أو تمت معالجته');await SystemDB.run(`UPDATE ai_tasks SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3`,[decision==='approved'?'queued':'cancelled',a.task_id,uid]);await audit(uid,'approval.decided',{decision,note},{task_id:a.task_id});return a;},
  async alerts(uid){return SystemDB.all(`SELECT * FROM ai_alerts WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[uid]);},
  async resolveAlert(uid,id){const row=await SystemDB.get(`UPDATE ai_alerts SET status='resolved',resolved_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING *`,[id,uid]);if(!row)throw new Error('التنبيه غير موجود');return row;},
  async ingestEvent(uid,type,payload={},idem){const key=idem||`${type}:${JSON.stringify(payload).slice(0,200)}`;const row=await SystemDB.get(`INSERT INTO ai_events(user_id,event_type,payload,idempotency_key) VALUES($1,$2,$3,$4) ON CONFLICT(event_type,idempotency_key) DO NOTHING RETURNING *`,[uid,type,JSON.stringify(payload),key]);if(row)EventBus.emit(type,{userId:uid,...payload,eventId:row.id});return row;},
  async executeTask(task){const now=new Date();await SystemDB.run(`UPDATE ai_tasks SET status='running',started_at=COALESCE(started_at,NOW()),updated_at=NOW() WHERE id=$1 AND status='queued'`,[task.id]);await emit('ai:task_update',{userId:task.user_id,taskId:task.id,status:'running'});let result;try{if(task.task_type==='analyze_performance')result=await AIEngine.analyzePerformance(task.payload||{});else result={accepted:true,mode:'guarded',message:'تم تنفيذ المهمة الحتمية ضمن الصلاحيات المحددة',payload:task.payload||{}};await SystemDB.run(`UPDATE ai_tasks SET status='success',result=$1,finished_at=NOW(),updated_at=NOW() WHERE id=$2`,[JSON.stringify(result),task.id]);await audit(task.user_id,'task.success',{result},{task_id:task.id});await emit('ai:task_update',{userId:task.user_id,taskId:task.id,status:'success'});}catch(e){await SystemDB.run(`UPDATE ai_tasks SET status='failed',error_code=$1,error_message=$2,finished_at=NOW(),updated_at=NOW() WHERE id=$3`,['EXECUTION_FAILED',e.message,task.id]);await SystemDB.run(`INSERT INTO ai_alerts(user_id,severity,source,description) VALUES($1,'high','ai_worker',$2)`,[task.user_id,e.message]);await audit(task.user_id,'task.failed',{error:e.message},{task_id:task.id});}},
  async tick(){if(workerBusy)return;workerBusy=true;try{const tasks=await SystemDB.all(`SELECT * FROM ai_tasks WHERE status='queued' ORDER BY priority ASC,created_at ASC LIMIT 5`,[]);for(const task of tasks)await this.executeTask(task);}finally{workerBusy=false;}},
  async startWorker(){if(timer)return;timer=setInterval(()=>this.tick().catch(e=>console.error('[AIWorker]',e.message)),1000);timer.unref?.();await this.tick();},
  stopWorker(){if(timer)clearInterval(timer);timer=null;},
  async registerCoreEvents(){for(const type of ['message.received','keyword.detected','link.detected','account.connected','account.disconnected','task.failed','task.completed'])EventBus.on(type,async data=>{if(!data?.userId)return;try{await this.ingestEvent(data.userId,type,data,data.eventId);}catch{}});}
};
module.exports=service;
