import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { io, Socket } from 'socket.io-client';
import { Activity, CheckCircle2, Clock3, Download, FileUp, Filter, Link2, Loader2, Pause, Play, RefreshCw, Search, Settings2, ShieldAlert, Square, Users, XCircle } from 'lucide-react';
import { API, authFetch, TOKEN_KEY } from '@/utils/api';
import { cn } from '@/utils/cn';
import { useToast } from '@/components/ui/ToastProvider';
import DirectPublishSection from '@/components/DirectPublishSection';

type LinkItem = { id: string; canonical_url: string; last_status?: string; last_error?: string };
type Account = { id: string; name: string; phone_number?: string; status?: string; health_status?: string };
type Operation = { id: string; account_id: string; account_name: string; link_id: string; url: string; status: string; last_error?: string; attempt_count?: number };
type Dashboard = { task: any; operations: Operation[]; events: any[]; stats: Record<string, number>; progress: number };

const STATUS: Record<string, { label: string; tone: string; Icon: any }> = {
  pending: { label: 'انتظار', tone: 'text-amber-400 bg-amber-500/10', Icon: Clock3 }, processing: { label: 'تنفيذ', tone: 'text-sky-400 bg-sky-500/10', Icon: Loader2 }, success: { label: 'نجاح', tone: 'text-emerald-400 bg-emerald-500/10', Icon: CheckCircle2 }, failed: { label: 'فشل', tone: 'text-rose-400 bg-rose-500/10', Icon: XCircle }, retry: { label: 'إعادة محاولة', tone: 'text-orange-400 bg-orange-500/10', Icon: RefreshCw }, review: { label: 'مراجعة', tone: 'text-violet-400 bg-violet-500/10', Icon: ShieldAlert }, skipped: { label: 'تخطي', tone: 'text-slate-400 bg-slate-500/10', Icon: Square }, paused: { label: 'متوقف', tone: 'text-yellow-400 bg-yellow-500/10', Icon: Pause },
};
function Badge({ status }: { status?: string }) { const meta = STATUS[status || 'pending'] || STATUS.pending; const Icon = meta.Icon; return <span className={cn('inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-bold whitespace-nowrap', meta.tone)}><Icon className={cn('h-3.5 w-3.5', status === 'processing' && 'animate-spin')} />{meta.label}</span>; }
function Card({ label, value, Icon, tone = 'text-emerald-400' }: any) { return <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-4"><Icon className={cn('mb-3 h-5 w-5', tone)} /><strong className="block text-2xl font-black">{value}</strong><span className="mt-1 block text-xs text-[var(--text-muted)]">{label}</span></div>; }

export default function LinkImportView() {
  const { addToast } = useToast(); const fileRef = useRef<HTMLInputElement>(null); const socketRef = useRef<Socket | null>(null);
  const [links, setLinks] = useState<LinkItem[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [selectedLinks, setSelectedLinks] = useState<Set<string>>(new Set()); const [selectedAccounts, setSelectedAccounts] = useState<Set<string>>(new Set());
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [taskId, setTaskId] = useState<string | null>(null); const [summary, setSummary] = useState<any>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [importing, setImporting] = useState(false); const [minDelay, setMinDelay] = useState(60); const [maxDelay, setMaxDelay] = useState(180); const [maxRetries, setMaxRetries] = useState(2);
  const load = useCallback(async () => { const [l, a] = await Promise.all([authFetch(`${API}/telegram/link-import/links?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`), authFetch(`${API}/accounts`)]); const ld = await l.json(); const ad = await a.json(); if (ld.success) setLinks(ld.links || []); if (ad.success) setAccounts(ad.accounts || []); }, [search, status]);
  const refreshDashboard = useCallback(async (id: string) => { const r = await authFetch(`${API}/telegram/link-import/tasks/${id}`); const d = await r.json(); if (d.success) setDashboard(d); }, []);
  useEffect(() => { load().catch(() => addToast({ title: 'تعذر تحميل بيانات القسم', type: 'error' })); }, [load, addToast]);
  useEffect(() => { const socket = io(window.location.origin, { path: '/socket.io', transports: ['websocket', 'polling'] }); socketRef.current = socket; socket.on('connect', () => { const u = JSON.parse(localStorage.getItem('wa_user') || '{}'); socket.emit('join_user', { userId: u.id, token: localStorage.getItem(TOKEN_KEY) || '' }); }); socket.on('link_import:event', (event: any) => { if (taskId && event.taskId === taskId) refreshDashboard(taskId); }); socket.on('link_import:source_completed', (source: any) => { setSummary(source); load(); }); return () => socket.disconnect(); }, [taskId, refreshDashboard, load]);
  useEffect(() => { if (!taskId) return; const id = window.setInterval(() => refreshDashboard(taskId), 5000); return () => window.clearInterval(id); }, [taskId, refreshDashboard]);
  const toggle = (setter: any, id: string) => setter((old: Set<string>) => { const next = new Set(old); next.has(id) ? next.delete(id) : next.add(id); return next; });
  async function importWord(file?: File) { if (!file) return; setImporting(true); setSummary(null); try { const buf = new Uint8Array(await file.arrayBuffer()); let binary = ''; for (let i = 0; i < buf.length; i += 0x8000) binary += String.fromCharCode(...buf.subarray(i, i + 0x8000)); const r = await authFetch(`${API}/telegram/link-import/word`, { method: 'POST', body: JSON.stringify({ filename: file.name, contentBase64: btoa(binary) }) }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.error || 'تعذر قراءة الملف'); setSummary(d.summary); await load(); addToast({ title: 'تم استيراد الروابط فعليًا', type: 'success' }); } catch (e: any) { addToast({ title: e.message, type: 'error' }); } finally { setImporting(false); } }
  async function start() { if (!selectedLinks.size || !selectedAccounts.size) return addToast({ title: 'اختر روابط وحسابات قبل التشغيل', type: 'error' }); setBusy(true); try { const r = await authFetch(`${API}/telegram/link-import/tasks`, { method: 'POST', body: JSON.stringify({ linkIds: [...selectedLinks], accountIds: [...selectedAccounts], settings: { minDelaySeconds: minDelay, maxDelaySeconds: maxDelay, maxRetries } }) }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.error || 'تعذر إنشاء المهمة'); setTaskId(d.task.id); await refreshDashboard(d.task.id); addToast({ title: `تم إنشاء ${d.totalOperations} عملية مستقلة`, type: 'success' }); } catch (e: any) { addToast({ title: e.message, type: 'error' }); } finally { setBusy(false); } }
  async function control(next: string) { if (!taskId) return; const r = await authFetch(`${API}/telegram/link-import/tasks/${taskId}`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); const d = await r.json(); if (!r.ok || !d.success) addToast({ title: d.error || 'تعذر تغيير حالة المهمة', type: 'error' }); await refreshDashboard(taskId); }
  async function retry(operationId: string) { const r = await authFetch(`${API}/telegram/link-import/operations/${operationId}/retry`, { method: 'POST' }); const d = await r.json(); if (!r.ok || !d.success) addToast({ title: d.error || 'تعذرت إعادة المحاولة', type: 'error' }); if (taskId) await refreshDashboard(taskId); }
  async function exportLinks() { const r = await authFetch(`${API}/telegram/link-import/export?search=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`); if (!r.ok) return addToast({ title: 'تعذر تصدير التقرير', type: 'error' }); const blob = await r.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'whatsapp-link-import.csv'; anchor.click(); URL.revokeObjectURL(url); }
  const matrix = useMemo(() => { const map = new Map<string, Operation>(); dashboard?.operations.forEach(o => map.set(`${o.account_id}:${o.link_id}`, o)); return map; }, [dashboard]); const readyAccounts = accounts.filter(a => a.status === 'connected' && !['protected', 'blocked'].includes(a.health_status || ''));
  return <div dir="rtl" className="space-y-6 pb-12">
    <header className="rounded-3xl border border-[var(--border-default)] bg-gradient-to-br from-[var(--bg-surface)] to-[var(--bg-elevated)] p-6 shadow-xl"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="mb-2 flex items-center gap-2 text-emerald-400"><Link2 className="h-5 w-5" /><span className="text-xs font-black tracking-[.18em]">الروابط / مركز التشغيل</span></div><h1 className="text-3xl font-black">استيراد الروابط</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--text-muted)]">استيراد حقيقي من Word، تحقق وتوحيد للروابط، ثم تشغيل مستقل لكل علاقة حساب × رابط عبر Queue آمنة مع حماية الحسابات وسجل لحظي.</p></div><button title="اختيار ملف DOCX" onClick={() => fileRef.current?.click()} disabled={importing} className="inline-flex items-center gap-2 rounded-2xl bg-emerald-500 px-5 py-3 text-sm font-black text-white shadow-lg shadow-emerald-500/20 hover:bg-emerald-400 disabled:opacity-50">{importing ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileUp className="h-4 w-4" />}استيراد روابط Word</button><input ref={fileRef} hidden type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e => importWord(e.target.files?.[0])} /></div><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8"><Card label="إجمالي الروابط" value={links.length} Icon={Link2} /><Card label="الحسابات الجاهزة" value={readyAccounts.length} Icon={Users} tone="text-sky-400" /><Card label="العمليات" value={dashboard?.stats?.total || 0} Icon={Activity} tone="text-violet-400" /><Card label="الناجحة" value={dashboard?.stats?.success || 0} Icon={CheckCircle2} /><Card label="الفاشلة" value={dashboard?.stats?.failed || 0} Icon={XCircle} tone="text-rose-400" /><Card label="الانتظار" value={dashboard?.stats?.pending || 0} Icon={Clock3} tone="text-amber-400" /><Card label="مراجعة" value={dashboard?.stats?.review || 0} Icon={ShieldAlert} tone="text-violet-400" /><Card label="التقدم" value={`${dashboard?.progress || 0}%`} Icon={Activity} tone="text-sky-400" /></div></header>
    {summary && <section className="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><CheckCircle2 className="h-5 w-5 text-emerald-400" />نتيجة الاستيراد · {summary.filename}</h2><div className="grid grid-cols-2 gap-4 text-sm md:grid-cols-6"><Stat label="الإجمالي" value={summary.total} /><Stat label="جديد" value={summary.newCount} tone="text-emerald-400" /><Stat label="مكرر" value={summary.duplicateCount} tone="text-amber-400" /><Stat label="غير صالح" value={summary.invalidCount} tone="text-rose-400" /><Stat label="مراجعة" value={summary.reviewCount} tone="text-violet-400" /><Stat label="المدة" value={`${summary.processingMs}ms`} /></div></section>}
    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Panel title="الروابط المستوردة" icon={Link2} action={<div className="flex gap-2"><button title="تصدير CSV" onClick={exportLinks} className="rounded-lg p-2 text-[var(--text-muted)] hover:bg-[var(--bg-hover)]"><Download className="h-4 w-4" /></button><button onClick={() => setSelectedLinks(new Set(links.map(l => l.id)))} className="text-xs text-emerald-400">تحديد الكل</button></div>}><div className="mb-3 flex gap-2"><div className="relative flex-1"><Search className="absolute right-3 top-2.5 h-4 w-4 text-[var(--text-muted)]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="بحث في الروابط..." className="w-full rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] py-2 pr-9 pl-3 text-sm" dir="ltr" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 text-sm"><option value="">الكل</option><option value="success">نجاح</option><option value="failed">فشل</option><option value="review">مراجعة</option></select><Filter className="mt-2 h-4 w-4 text-[var(--text-muted)]" /></div><div className="max-h-80 space-y-2 overflow-auto">{links.length ? links.map(link => <label key={link.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-3 hover:border-emerald-500/40"><input type="checkbox" checked={selectedLinks.has(link.id)} onChange={() => toggle(setSelectedLinks, link.id)} className="h-4 w-4 accent-emerald-500" /><span className="min-w-0 flex-1 truncate text-sm" dir="ltr">{link.canonical_url}</span>{link.last_status && <Badge status={link.last_status} />}</label>) : <Empty text="لم يتم استيراد روابط بعد" />}</div></Panel>
      <Panel title="اختيار الحسابات" icon={Users} action={<button onClick={() => setSelectedAccounts(new Set(readyAccounts.map(a => a.id)))} className="text-xs text-sky-400">تحديد الجاهز</button>}><div className="space-y-2">{accounts.length ? accounts.map(account => <label key={account.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-3"><input type="checkbox" disabled={account.status !== 'connected' || ['protected', 'blocked'].includes(account.health_status || '')} checked={selectedAccounts.has(account.id)} onChange={() => toggle(setSelectedAccounts, account.id)} className="h-4 w-4 accent-sky-500" /><span className="min-w-0 flex-1"><strong className="block text-sm">{account.name}</strong><small className="text-xs text-[var(--text-muted)]">{account.phone_number || 'بدون رقم'}</small></span><Badge status={account.health_status === 'protected' ? 'review' : account.status === 'connected' ? 'success' : 'skipped'} /></label>) : <Empty text="لا توجد حسابات" />}</div></Panel></section>
    <section className="rounded-3xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-black"><Settings2 className="h-5 w-5 text-violet-400" />إعدادات التشغيل الآمن</h2><div className="grid gap-4 md:grid-cols-3"><Field label="الحد الأدنى للتأخير بالثواني" value={minDelay} setValue={setMinDelay} /><Field label="الحد الأعلى للتأخير بالثواني" value={maxDelay} setValue={setMaxDelay} /><Field label="أقصى عدد للمحاولات" value={maxRetries} setValue={setMaxRetries} /></div><div className="mt-4 flex flex-wrap gap-3"><button title="إنشاء مهام مستقلة وتشغيلها عبر Queue" onClick={start} disabled={busy || !selectedLinks.size || !selectedAccounts.size} className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}بدء الانضمام الآمن</button>{taskId && <><button onClick={() => control('paused')} className="inline-flex items-center gap-2 rounded-xl border border-amber-500/30 px-4 py-3 text-sm font-bold text-amber-400"><Pause className="h-4 w-4" />إيقاف مؤقت</button><button onClick={() => control('stopped')} className="inline-flex items-center gap-2 rounded-xl border border-rose-500/30 px-4 py-3 text-sm font-bold text-rose-400"><Square className="h-4 w-4" />إيقاف</button><button onClick={() => control('pending')} className="inline-flex items-center gap-2 rounded-xl border border-sky-500/30 px-4 py-3 text-sm font-bold text-sky-400"><RefreshCw className="h-4 w-4" />استئناف</button></>}</div></section>
    {dashboard && <section className="rounded-3xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black"><Activity className="h-5 w-5 text-violet-400" />مصفوفة الحساب × الرابط</h2><p className="mt-1 text-xs text-[var(--text-muted)]">تحديث لحظي من قاعدة البيانات والأحداث.</p></div><strong className="text-emerald-400">{dashboard.progress}% مكتمل</strong></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-[var(--bg-elevated)]"><div className="h-full rounded-full bg-gradient-to-l from-emerald-400 to-sky-400 transition-all" style={{ width: `${dashboard.progress}%` }} /></div><div className="overflow-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead><tr className="border-b border-[var(--border-default)] text-xs text-[var(--text-muted)]"><th className="p-3">الحساب</th>{[...selectedLinks].map(id => <th key={id} className="p-3" dir="ltr">{links.find(l => l.id === id)?.canonical_url.split('/').pop()}</th>)}</tr></thead><tbody>{accounts.filter(a => selectedAccounts.has(a.id)).map(a => <tr key={a.id} className="border-b border-[var(--border-default)]"><td className="p-3 font-bold">{a.name}</td>{[...selectedLinks].map(linkId => { const op = matrix.get(`${a.id}:${linkId}`); return <td key={linkId} className="p-3"><Badge status={op?.status} />{op && ['failed', 'review'].includes(op.status) && <button onClick={() => retry(op.id)} className="mr-2 text-xs text-sky-400 hover:underline">Retry</button>}</td>; })}</tr>)}</tbody></table></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><div><h3 className="mb-3 font-bold">النشاط المباشر</h3><div className="max-h-56 space-y-2 overflow-auto">{dashboard.events?.length ? dashboard.events.map((event: any) => <div key={event.id} className="rounded-xl bg-[var(--bg-elevated)] p-3 text-xs"><div className="flex items-center justify-between"><span className="font-bold">{event.event_type}</span><time className="text-[var(--text-muted)]">{new Date(event.created_at).toLocaleTimeString('ar-SA')}</time></div><pre className="mt-1 whitespace-pre-wrap text-[var(--text-muted)]">{JSON.stringify(event.payload)}</pre></div>) : <Empty text="لا يوجد نشاط بعد" />}</div></div><div><h3 className="mb-3 font-bold">حماية الحسابات</h3><div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm leading-7 text-[var(--text-muted)]">لا يتم تجاوز قيود WhatsApp أو التحايل عليها. الحساب غير المتصل أو المحمي يتوقف عن استقبال عمليات جديدة، والأخطاء الدائمة تنتقل إلى المراجعة بدل إعادة المحاولة بلا نهاية.</div></div></div></section>}
    <DirectPublishSection
      links={links}
      accounts={accounts}
      selectedLinks={selectedLinks}
      selectedAccounts={selectedAccounts}
      dashboard={dashboard}
      taskId={taskId}
      busy={busy}
      onToggleLink={(id) => toggle(setSelectedLinks, id)}
      onToggleAccount={(id) => toggle(setSelectedAccounts, id)}
      onSelectLinks={() => setSelectedLinks(new Set(links.map(link => link.id)))}
      onSelectAccounts={() => setSelectedAccounts(new Set(readyAccounts.map(account => account.id)))}
      onStart={start}
      onControl={control}
    />
  </div>;
}
function Panel({ title, icon: Icon, action, children }: any) { return <section className="rounded-3xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-black"><Icon className="h-5 w-5 text-emerald-400" />{title}</h2>{action}</div>{children}</section>; }
function Stat({ label, value, tone = '' }: any) { return <div><span className="block text-xs text-[var(--text-muted)]">{label}</span><strong className={cn('mt-1 block text-lg', tone)}>{value}</strong></div>; }
function Field({ label, value, setValue }: any) { return <label className="text-sm"><span className="mb-2 block text-xs text-[var(--text-muted)]">{label}</span><input type="number" min="0" value={value} onChange={e => setValue(Number(e.target.value))} className="w-full rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-2.5" /></label>; }
function Empty({ text }: { text: string }) { return <div className="py-10 text-center text-sm text-[var(--text-muted)]">{text}</div>; }
