'use strict';
const Service = require('../services/TelegramKeywordService');
const TelegramService = require('../services/TelegramService');
const { queryOne } = require('../../lib/postgres');
const Controller = {
  async dashboard(req,res){ try { return res.json({success:true,...await Service.dashboard(req.user.id,req.query)}); } catch(e){ return res.status(500).json({success:false,error:'تعذر تحميل مركز كلمات تيليجرام'}); } },
  async toggleChatPin(req,res){ try { return res.json({success:true,...await Service.toggleChatPin(req.user.id,req.body || {})}); } catch(e){ const status = e.code === 'PIN_LIMIT_REACHED' ? 409 : e.code === 'CHAT_ID_REQUIRED' || e.code === 'TELEGRAM_ACCOUNT_NOT_FOUND' ? 400 : 500; return res.status(status).json({success:false,error:e.message || 'تعذر تحديث تثبيت المحادثة',code:e.code || 'TELEGRAM_CHAT_PIN_FAILED'}); } },
  async accounts(req,res){ try { return res.json({success:true,accounts:await Service.accounts(req.user.id)}); } catch(e){ return res.status(500).json({success:false,error:'تعذر تحميل الحسابات'}); } },
  async create(req,res){ try { return res.status(201).json({success:true,keyword:await Service.createKeyword(req.user.id,req.body)}); } catch(e){ return res.status(400).json({success:false,error:e.message}); } },
  async update(req,res){ try { return res.json({success:true,keyword:await Service.updateKeyword(req.user.id,req.params.id,req.body)}); } catch(e){ return res.status(400).json({success:false,error:e.message}); } },
  async remove(req,res){ try { await Service.deleteKeyword(req.user.id,req.params.id); return res.json({success:true}); } catch(e){ return res.status(404).json({success:false,error:e.message}); } },
  async openDirectChat(req,res){ try { return res.json({success:true,...await Service.openDirectChat(req.user.id,req.params.id)}); } catch(e){ return res.status(e.code === 'ACCOUNT_OFFLINE' ? 409 : 400).json({success:false,error:e.message,code:e.code || 'TELEGRAM_CHAT_OPEN_FAILED'}); } },
  async reply(req,res){ try { return res.json({success:true,...await Service.reply(req.user.id,req.params.id,req.body.text)}); } catch(e){ return res.status(e.code === 'ACCOUNT_OFFLINE' ? 409 : 400).json({success:false,error:e.message,code:e.code || 'TELEGRAM_REPLY_FAILED'}); } },
  async ignore(req,res){ try { return res.json({success:true,...await Service.ignoreMessage(req.user.id,req.params.id)}); } catch(e){ console.error('[TelegramKeywordController.ignore]', { resultId: req.params.id, userId: req.user?.id, code: e.code, message: e.message }); return res.status(e.code === 'RESULT_NOT_FOUND' ? 404 : 500).json({success:false,error:e.message || 'تعذر تجاهل الرسالة',code:e.code || 'TELEGRAM_IGNORE_FAILED'}); } },
  async blockUser(req,res){ try { return res.json({success:true,...await Service.blockUser(req.user.id,req.params.id,req.body||{})}); } catch(e){ console.error('[TelegramKeywordController.blockUser]', { resultId:req.params.id, userId:req.user?.id, code:e.code, message:e.message }); const status=e.code==='RESULT_NOT_FOUND'||e.code==='SENDER_ID_MISSING'?404:500; return res.status(status).json({success:false,error:e.message||'تعذر حظر المستخدم بالكامل',code:e.code||'TELEGRAM_BLOCK_FAILED'}); } },
  async blockedUsers(req,res){ try { return res.json({success:true,users:await Service.listBlockedUsers(req.user.id,req.query||{})}); } catch(e){ return res.status(500).json({success:false,error:'تعذر تحميل المستخدمين المحظورين'}); } },
  async unblockUser(req,res){ try { return res.json({success:true,...await Service.unblockUser(req.user.id,req.params.id)}); } catch(e){ return res.status(e.code==='BLOCKED_USER_NOT_FOUND'?404:500).json({success:false,error:e.message||'تعذر إلغاء حظر المستخدم',code:e.code||'TELEGRAM_UNBLOCK_FAILED'}); } },
  async worker(req,res){ try { const accounts=await Service.accounts(req.user.id); return res.json({success:true,workers:accounts.map(a=>({accountId:a.id,status:a.status,worker:TelegramService.getWorker(a.id)?.status||'stopped',lastCheck:TelegramService.getWorker(a.id)?.lastCheck||null,error:TelegramService.getWorker(a.id)?.error||null}))}); } catch(e){ return res.status(500).json({success:false,error:'تعذر تحميل حالة العمال'}); } },
};
module.exports = Controller;
