import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {io} from 'socket.io-client';
import {Activity, AlertTriangle, Bot, CheckCircle2, CirclePlay, Clock3, Database, GitBranch, ListChecks, LockKeyhole, Pause, Play, Plus, RefreshCw, ShieldCheck, Sparkles, Terminal, Wrench, XCircle, Zap} from 'lucide-react';
import {API,authFetch,TOKEN_KEY} from '@/utils/api';
import {Card,CardContent} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {useToast} from '@/components/ui/ToastProvider';
import {cn} from '@/utils/cn';

type Tab='dashboard'|'agents'|'workflows'|'tasks'|'approvals'|'alerts'|'tools';
const statusText:any={active:'نشط',paused:'متوقف مؤقتاً',disabled:'معطل',draft:'مسودة',queued:'منتظر',running:'قيد التنفيذ',success:'نجح',failed:'فشل',waiting_approval:'بانتظار الموافقة',blocked:'محظور',cancelled:'ملغى',open:'مفتوح',resolved:'تمت المعالجة'};
export default function AIAutomationView(){
 const toast=useToast();const addToast=toast.addToast;const [tab,setTab]=useState<Tab>('dashboard');const [data,setData]=useState<any>({stats:{},recent:[],errors:[],approvals:[],tools:[]});const [agents,setAgents]=useState<any[]>([]);const [workflows,setWorkflows]=useState<any[]>([]);const [tasks,setTasks]=useState<any[]>([]);const [approvals,setApprovals]=useState<any[]>([]);const [alerts,setAlerts]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [agentName,setAgentName]=useState('');const [workflowName,setWorkflowName]=useState('');const [taskName,setTaskName]=useState('');
 const load=useCallback(async()=>{try{const [d,a,w,t,ap,al]=await Promise.all([authFetch(`${API}/ai-center/dashboard`),authFetch(`${API}/ai-center/agents`),authFetch(`${API}/ai-center/workflows`),authFetch(`${API}/ai-center/tasks`),authFetch(`${API}/ai-center/approvals`),authFetch(`${API}/ai-center/alerts`)]);const j=await d.json(),ja=await a.json(),jw=await w.json(),jt=await t.json(),jp=await ap.json(),jl=await al.json();if(j.success)setData(j);if(ja.success)setAgents(ja.agents||[]);if(jw.success)setWorkflows(jw.workflows||[]);if(jt.success)setTasks(jt.tasks||[]);if(jp.success)setApprovals(jp.approvals||[]);if(jl.success)setAlerts(jl.alerts||[]);}catch(e){addToast({title:'تعذر تحديث مركز الذكاء',type:'error'});}},[addToast]);
 useEffect(()=>{load();const timer=window.setInterval(load,5000);const s=io(window.location.origin,{path:'/socket.io',transports:['websocket','polling']});s.on('connect',()=>{const u=JSON.parse(localStorage.getItem('wa_user')||'{}');s.emit('join_user',{userId:u.id,token:localStorage.getItem(TOKEN_KEY)||''});});s.on('ai:task_update',load);return()=>{window.clearInterval(timer);s.disconnect();};},[load]);
 const createAgent=async()=>{if(!agentName.trim())return;setBusy(true);try{const r=await authFetch(`${API}/ai-center/agents`,{method:'POST',body:JSON.stringify({name:agentName,description:'وكيل مدار من مركز الذكاء',goal:'تحليل البيانات ضمن الصلاحيات',autonomy:'supervised',tools:['database_read','statistics']})});const d=await r.json();if(!d.success)throw Error(d.error);setAgentName('');await load();addToast({title:'تم إنشاء الوكيل وحالته متوقفة للمراجعة',type:'success'});}catch(e:any){addToast({title:e.message,type:'error'});}finally{setBusy(false);}};
 const createWorkflow=async()=>{if(!workflowName.trim())return;setBusy(true);try{const r=await authFetch(`${API}/ai-center/workflows`,{method:'POST',body:JSON.stringify({name:workflowName,trigger_type:'manual',nodes:[{type:'trigger',label:'حدث'},{type:'ai',label:'تحليل'},{type:'approval',label:'موافقة'},{type:'action',label:'إجراء'},{type:'verify',label:'تحقق'},{type:'log',label:'سجل'}]})});const d=await r.json();if(!d.success)throw Error(d.error);setWorkflowName('');await load();addToast({title:'تم حفظ Workflow كمسودة',type:'success'});}catch(e:any){addToast({title:e.message,type:'error'});}finally{setBusy(false);}};
 const createTask=async()=>{if(!taskName.trim())return;setBusy(true);try{const r=await authFetch(`${API}/ai-center/tasks`,{method:'POST',body:JSON.stringify({name:taskName,task_type:'manual',payload:{requested_from:'dashboard'},risk_score:0,idempotency_key:`manual:${taskName}`})});const d=await r.json();if(!d.success)throw Error(d.error);setTaskName('');await load();addToast({title:'تم وضع المهمة في Queue',type:'success'});}catch(e:any){addToast({title:e.message,type:'error'});}finally{setBusy(false);}};
 const action=async(url:string,method:string,body:any={})=>{try{const r=await authFetch(url,{method,body:JSON.stringify(body)});const d=await r.json();if(!d.success)throw Error(d.error);await load();addToast({title:'تم تنفيذ العملية بنجاح',type:'success'});}catch(e:any){addToast({title:e.message,type:'error'});}};
 const s=data.stats||{};const cards=[['الوكلاء النشطون',s.agents?.active||0,Bot,'text-violet-400'],['Workflows النشطة',s.workflows?.active||0,GitBranch,'text-cyan-400'],['المهام الجارية',s.tasks?.active||0,CirclePlay,'text-emerald-400'],['المهام المنتظرة',s.tasks?.queued||0,Clock3,'text-amber-400'],['المكتملة',s.tasks?.completed||0,CheckCircle2,'text-blue-400'],['الفاشلة',s.tasks?.failed||0,XCircle,'text-red-400'],['بانتظار الموافقة',s.tasks?.approvals||0,ShieldCheck,'text-orange-400'],['الأحداث المحللة',s.events||0,Activity,'text-pink-400']];
 const tabs:[Tab,string,any][]=[['dashboard','لوحة القيادة',Activity],['agents','الوكلاء',Bot],['workflows','Workflows',GitBranch],['tasks','المهام',ListChecks],['approvals','الموافقات',ShieldCheck],['alerts','التنبيهات',AlertTriangle],['tools','الأدوات',Wrench]];
 return <div dir="rtl" className="h-full overflow-y-auto bg-[var(--bg-app)] text-[var(--text-primary)]"><header className="border-b border-[var(--border-default)] bg-[var(--bg-surface)] px-6 py-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Sparkles className="w-6 h-6 text-violet-400"/> مركز الذكاء والأتمتة</h1><p className="text-xs text-[var(--text-muted)] mt-1">محرك مركزي للعملاء والوكلاء والمهام مع حواجز وموافقات بشرية.</p></div><Button onClick={load} variant="outline" className="gap-2"><RefreshCw className="w-4 h-4"/> تحديث حي</Button></div><div className="grid grid-cols-2 md:grid-cols-6 gap-2 mt-5">{[['AI ENGINE',s.ai_online?'متصل':'غير مهيأ',s.ai_online],['AUTOMATION',s.automation_online?'يعمل':'متوقف',s.automation_online],['WORKERS',s.tasks?.active?`${s.tasks.active} نشط`:'جاهز',true],['QUEUE',s.tasks?.queued?'مشغولة':'طبيعية',true],['DATABASE','متصلة',true],['GUARDRAILS','مفعلة',true]].map(([l,v,ok])=><div key={String(l)} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-2"><p className="text-[10px] text-[var(--text-muted)]">{l}</p><p className={cn('text-xs font-bold mt-1 flex items-center gap-1',ok?'text-emerald-400':'text-amber-400')}><span className={cn('w-1.5 h-1.5 rounded-full',ok?'bg-emerald-400':'bg-amber-400')}/>{v}</p></div>)}</div></header><div className="flex gap-1 px-6 pt-4 overflow-x-auto">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={cn('flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-2 text-sm',tab===id?'bg-violet-600 text-white':'text-[var(--text-muted)] hover:bg-[var(--bg-hover)]')}><Icon className="w-4 h-4"/>{label}</button>)}</div><main className="p-6 space-y-5">
 {tab==='dashboard'&&<><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">{cards.map(([l,v,Icon,c])=><Card key={String(l)}><CardContent className="p-3"><Icon className={cn('w-5 h-5',String(c))}/><p className="text-xs text-[var(--text-muted)] mt-2">{l}</p><p className="text-2xl font-bold mt-1">{String(v)}</p></CardContent></Card>)}</div><div className="grid lg:grid-cols-2 gap-5"><Card><CardContent className="p-4"><h2 className="font-bold mb-3">آخر العمليات</h2>{data.recent?.length?data.recent.map((t:any)=><div key={t.id} className="flex items-center justify-between border-b border-[var(--border-default)] py-3 text-sm"><span>{t.name}</span><Badge variant={t.status==='success'?'success':t.status==='failed'?'danger':'info'}>{statusText[t.status]||t.status}</Badge></div>):<p className="text-sm text-[var(--text-muted)]">لا توجد عمليات بعد.</p>}</CardContent></Card><Card><CardContent className="p-4"><h2 className="font-bold mb-3">حواجز التشغيل</h2><div className="space-y-3 text-sm"><p className="flex gap-2"><LockKeyhole className="w-4 h-4 text-emerald-400"/>العمليات عالية الخطورة تتوقف للموافقة البشرية.</p><p className="flex gap-2"><Database className="w-4 h-4 text-cyan-400"/>النطاق معزول حسب المستخدم وقاعدة البيانات.</p><p className="flex gap-2"><Terminal className="w-4 h-4 text-violet-400"/>الأدوات لا تُمنح للوكلاء تلقائياً.</p></div></CardContent></Card></div></>}
 {tab==='agents'&&<Card><CardContent className="p-4"><div className="flex gap-2 mb-4"><input value={agentName} onChange={e=>setAgentName(e.target.value)} placeholder="اسم الوكيل الجديد" className="flex-1 rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-2 text-sm"/><Button disabled={busy} onClick={createAgent} className="gap-1"><Plus className="w-4 h-4"/> إنشاء وكيل</Button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{agents.map(a=><div key={a.id} className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-4"><div className="flex justify-between"><div><p className="font-bold">{a.name}</p><p className="text-xs text-[var(--text-muted)] mt-1">{a.autonomy} · {a.model}</p></div><Badge variant={a.status==='active'?'success':'warning'}>{statusText[a.status]}</Badge></div><p className="text-xs mt-3 text-[var(--text-muted)]">الأدوات: {(a.tools||[]).join('، ')||'لا توجد'}</p><Button size="sm" variant="outline" className="mt-3" onClick={()=>action(`${API}/ai-center/agents/${a.id}`,'PATCH',{status:a.status==='active'?'paused':'active'})}>{a.status==='active'?<><Pause className="w-3 h-3 ml-1"/> إيقاف</>:<><Play className="w-3 h-3 ml-1"/> تفعيل</>}</Button></div>)}</div></CardContent></Card>}
 {tab==='workflows'&&<Card><CardContent className="p-4"><div className="flex gap-2 mb-4"><input value={workflowName} onChange={e=>setWorkflowName(e.target.value)} placeholder="اسم Workflow الجديد" className="flex-1 rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-2 text-sm"/><Button disabled={busy} onClick={createWorkflow} className="gap-1"><Plus className="w-4 h-4"/> حفظ Workflow</Button></div>{workflows.map(w=><div key={w.id} className="border border-[var(--border-default)] rounded-xl p-4 mb-3"><div className="flex justify-between"><div><p className="font-bold">{w.name}</p><p className="text-xs text-[var(--text-muted)]">الإصدار {w.version} · المشغل: {w.trigger_type} · {(w.nodes||[]).length} عقد</p></div><Badge variant={w.status==='active'?'success':'outline'}>{statusText[w.status]}</Badge></div><div className="flex flex-wrap gap-2 mt-3">{(w.nodes||[]).map((n:any,i:number)=><span key={i} className="rounded-lg bg-[var(--bg-elevated)] px-2 py-1 text-xs">{n.label||n.type}</span>)}</div><Button size="sm" className="mt-3" onClick={()=>action(`${API}/ai-center/workflows/${w.id}/status`,'PATCH',{status:w.status==='active'?'paused':'active'})}>{w.status==='active'?'إيقاف Workflow':'تفعيل Workflow'}</Button></div>)}</CardContent></Card>}
 {tab==='tasks'&&<Card><CardContent className="p-4"><div className="flex gap-2 mb-4"><input value={taskName} onChange={e=>setTaskName(e.target.value)} placeholder="اسم المهمة" className="flex-1 rounded-xl border border-[var(--border-default)] bg-[var(--bg-elevated)] px-3 py-2 text-sm"/><Button disabled={busy} onClick={createTask} className="gap-1"><Plus className="w-4 h-4"/> تشغيل مهمة</Button></div>{tasks.map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--border-default)] py-3"><div><p className="font-semibold">{t.name}</p><p className="text-xs text-[var(--text-muted)]">{t.task_type} · خطورة {t.risk_score} · محاولات {t.retry_count}</p></div><div className="flex items-center gap-2"><Badge variant={t.status==='success'?'success':t.status==='failed'?'danger':t.status==='waiting_approval'?'warning':'info'}>{statusText[t.status]||t.status}</Badge>{['queued','running'].includes(t.status)&&<Button size="sm" variant="outline" onClick={()=>action(`${API}/ai-center/tasks/${t.id}`,'PATCH',{action:'cancel'})}>إلغاء</Button>}{t.status==='failed'&&<Button size="sm" onClick={()=>action(`${API}/ai-center/tasks/${t.id}`,'PATCH',{action:'retry'})}>إعادة</Button>}</div></div>)}</CardContent></Card>}
 {tab==='approvals'&&<Card><CardContent className="p-4">{approvals.length?approvals.map(a=><div key={a.id} className="border border-orange-400/30 rounded-xl p-4 mb-3"><div className="flex justify-between"><div><p className="font-bold">{a.name}</p><p className="text-sm text-[var(--text-muted)] mt-1">{a.reason}</p></div><Badge variant="warning">خطورة {a.risk_score}</Badge></div><div className="flex gap-2 mt-3"><Button onClick={()=>action(`${API}/ai-center/approvals/${a.id}`,'PATCH',{decision:'approved'})} className="gap-1"><CheckCircle2 className="w-4 h-4"/> موافقة</Button><Button variant="outline" onClick={()=>action(`${API}/ai-center/approvals/${a.id}`,'PATCH',{decision:'rejected'})} className="gap-1 text-red-400"><XCircle className="w-4 h-4"/> رفض</Button></div></div>):<p className="text-sm text-[var(--text-muted)]">لا توجد طلبات موافقة معلقة.</p>}</CardContent></Card>}
 {tab==='alerts'&&<Card><CardContent className="p-4">{alerts.map(a=><div key={a.id} className="flex items-center justify-between gap-3 border-b border-[var(--border-default)] py-3"><div><p className="font-semibold">{a.description}</p><p className="text-xs text-[var(--text-muted)]">{a.source} · {new Date(a.created_at).toLocaleString('ar-SA')}</p></div>{a.status==='open'&&<Button size="sm" variant="outline" onClick={()=>action(`${API}/ai-center/alerts/${a.id}/resolve`,'PATCH',{})}>معالجة</Button>}</div>)}</CardContent></Card>}
 {tab==='tools'&&<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{(data.tools||[]).map((t:any)=><Card key={t.name}><CardContent className="p-4"><div className="flex justify-between"><Wrench className="w-5 h-5 text-cyan-400"/><Badge variant={t.risk==='high'?'danger':t.risk==='medium'?'warning':'success'}>{t.risk}</Badge></div><p className="font-bold mt-3">{t.label}</p><p className="text-xs text-[var(--text-muted)] mt-1">{t.description}</p><p className="text-[10px] text-[var(--text-muted)] mt-3">لا يمكن استخدام الأداة إلا من وكيل مصرح له.</p></CardContent></Card>)}</div>}
 </main></div>;
}
