import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, CheckCircle2, Clock3, Download, Loader2, RefreshCw, TrendingUp, Users, XCircle } from 'lucide-react';
import { API, authFetch } from '../utils/api';
import { useToast } from '../components/ui/ToastProvider';
import { cn } from '@/utils/cn';

type Report = {
  generatedAt: string;
  summary: { links: { total: number; valid: number; invalid: number; duplicates: number }; jobs: { total: number; completed: number; successful: number; failed: number; deferred: number; successRate: number; errorRate: number } };
  accounts: Array<{ id: string; name: string; status: string; health_status?: string; jobs: number; successful: number; failed: number; last_error?: string; next_operation?: string }>;
  daily: Array<{ day: string; total: number; successful: number; failed: number }>;
  hourly: Array<{ hour: number; total: number; successful: number }>;
};

function Stat({ label, value, icon: Icon, tone }: { label: string; value: string | number; icon: any; tone: string }) { return <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-4"><div className="flex items-start justify-between"><div><p className="text-xs text-[var(--text-muted)]">{label}</p><strong className="mt-2 block text-2xl font-black">{value}</strong></div><div className={cn('rounded-xl p-2.5', tone)}><Icon className="h-5 w-5" /></div></div></div>; }
function dateLabel(value: string) { try { return new Date(value).toLocaleDateString('ar-SA', { month: 'short', day: 'numeric' }); } catch { return value; } }

export default function JoinAutomationReportsView() {
  const { addToast } = useToast();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const fetchReport = useCallback(async () => { setLoading(true); try { const response = await authFetch(`${API}/telegram/join-automation/report`); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'تعذر تحميل التقرير'); setReport(data); } catch (error: any) { addToast({ title: error.message || 'فشل تحميل التقرير', type: 'error' }); } finally { setLoading(false); } }, [addToast]);
  useEffect(() => { fetchReport(); }, [fetchReport]);
  const maxDaily = useMemo(() => Math.max(1, ...(report?.daily || []).map(item => Number(item.total))), [report?.daily]);
  const maxHourly = useMemo(() => Math.max(1, ...(report?.hourly || []).map(item => Number(item.total))), [report?.hourly]);
  async function exportReport() { setBusy(true); try { const response = await authFetch(`${API}/telegram/join-automation/logs/export`); if (!response.ok) throw new Error('لا يوجد سجل قابل للتصدير'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'join-automation-report.csv'; a.click(); URL.revokeObjectURL(url); addToast({ title: 'تم تصدير التقرير', type: 'success' }); } catch (error: any) { addToast({ title: error.message || 'فشل التصدير', type: 'error' }); } finally { setBusy(false); } }

  return <main className="mx-auto w-full max-w-[1500px] space-y-5 p-4 pb-10 sm:p-6" dir="rtl"><header className="flex flex-wrap items-start justify-between gap-4 rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/10 to-[var(--bg-surface)] p-6"><div className="flex items-start gap-3"><div className="rounded-2xl bg-violet-500/15 p-3 text-violet-300"><BarChart3 className="h-7 w-7" /></div><div><p className="text-xs font-bold text-violet-300">أتمتة الانضمام</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">تقارير الأتمتة</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--text-muted)]">ملخص حي مبني على المهام والروابط والأحداث المسجلة في قاعدة البيانات، دون أرقام تجريبية.</p></div></div><div className="flex gap-2"><button type="button" onClick={fetchReport} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-default)] px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4" />تحديث</button><button type="button" onClick={exportReport} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-3 py-2 text-xs font-black text-white disabled:opacity-50"><Download className="h-4 w-4" />تصدير</button></div></header>
    {loading ? <div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-14 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-violet-300" /></div> : report ? <><section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8"><Stat label="إجمالي الروابط" value={report.summary.links.total} icon={Activity} tone="bg-cyan-500/10 text-cyan-300" /><Stat label="الروابط الصالحة" value={report.summary.links.valid} icon={CheckCircle2} tone="bg-emerald-500/10 text-emerald-300" /><Stat label="غير الصالحة" value={report.summary.links.invalid} icon={XCircle} tone="bg-rose-500/10 text-rose-300" /><Stat label="المكررات" value={report.summary.links.duplicates} icon={RefreshCw} tone="bg-amber-500/10 text-amber-300" /><Stat label="إجمالي العمليات" value={report.summary.jobs.total} icon={BarChart3} tone="bg-indigo-500/10 text-indigo-300" /><Stat label="المكتملة" value={report.summary.jobs.completed} icon={CheckCircle2} tone="bg-violet-500/10 text-violet-300" /><Stat label="نسبة النجاح" value={`${report.summary.jobs.successRate}%`} icon={TrendingUp} tone="bg-emerald-500/10 text-emerald-300" /><Stat label="نسبة الخطأ" value={`${report.summary.jobs.errorRate}%`} icon={XCircle} tone="bg-rose-500/10 text-rose-300" /></section>
      <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-5"><div className="mb-5 flex items-center gap-3"><Activity className="h-5 w-5 text-cyan-300" /><div><h2 className="font-black">النشاط حسب اليوم</h2><p className="text-xs text-[var(--text-muted)]">آخر 31 يومًا</p></div></div><div className="flex h-56 items-end gap-2 overflow-x-auto pb-6">{[...(report.daily || [])].reverse().map(item => <div key={item.day} className="flex h-full min-w-8 flex-1 flex-col items-center justify-end gap-2"><div className="flex h-full w-full items-end justify-center gap-0.5"><div className="w-2 rounded-t bg-cyan-400" style={{ height: `${Math.max(4, item.successful / maxDaily * 100)}%` }} title={`نجاح: ${item.successful}`} /><div className="w-2 rounded-t bg-rose-400" style={{ height: `${Math.max(4, item.failed / maxDaily * 100)}%` }} title={`فشل: ${item.failed}`} /></div><span className="rotate-45 text-[9px] text-[var(--text-muted)]">{dateLabel(item.day)}</span></div>)}</div></div><div className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-5"><div className="mb-5 flex items-center gap-3"><Clock3 className="h-5 w-5 text-amber-300" /><div><h2 className="font-black">النشاط حسب الساعة</h2><p className="text-xs text-[var(--text-muted)]">توزيع العمليات حسب وقت تسجيلها</p></div></div><div className="flex h-56 items-end gap-1 pb-5">{Array.from({ length: 24 }, (_, hour) => { const item = report.hourly?.find(row => Number(row.hour) === hour); return <div key={hour} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><div className="w-full rounded-t bg-violet-400/80" style={{ height: `${Math.max(item?.total ? 4 : 0, Number(item?.total || 0) / maxHourly * 100)}%` }} title={`${hour}:00 — ${item?.total || 0}`} /><span className="text-[9px] text-[var(--text-muted)]">{hour}</span></div>; })}</div></div></section>
      <section className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-elevated)] p-5"><div className="mb-4 flex items-center gap-3"><Users className="h-5 w-5 text-emerald-300" /><div><h2 className="font-black">نشاط الحسابات</h2><p className="text-xs text-[var(--text-muted)]">عدد العمليات ونسب النجاح والفشل لكل حساب</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-right text-xs"><thead className="text-[var(--text-muted)]"><tr><th className="p-3">الحساب</th><th className="p-3">الحالة</th><th className="p-3">العمليات</th><th className="p-3">نجاح</th><th className="p-3">فشل</th><th className="p-3">نسبة النجاح</th><th className="p-3">العملية القادمة</th><th className="p-3">آخر خطأ</th></tr></thead><tbody>{report.accounts.length ? report.accounts.map(account => <tr key={account.id} className="border-t border-[var(--border-default)]"><td className="p-3 font-bold">{account.name}</td><td className="p-3"><span className="inline-flex items-center gap-1"><span className={cn('h-2 w-2 rounded-full', account.status === 'connected' ? 'bg-emerald-400' : 'bg-rose-400')} />{account.status}</span></td><td className="p-3">{account.jobs}</td><td className="p-3 text-emerald-300">{account.successful}</td><td className="p-3 text-rose-300">{account.failed}</td><td className="p-3">{account.jobs ? `${Math.round(account.successful / account.jobs * 100)}%` : '—'}</td><td className="p-3">{account.next_operation ? new Date(account.next_operation).toLocaleString('ar-SA') : '—'}</td><td className="max-w-64 truncate p-3 text-rose-200">{account.last_error || '—'}</td></tr>) : <tr><td colSpan={8} className="p-10 text-center text-[var(--text-muted)]">لا توجد عمليات مسجلة بعد.</td></tr>}</tbody></table></div></section></> : <div className="rounded-2xl border border-rose-400/20 bg-rose-500/5 p-10 text-center text-sm">تعذر تحميل التقرير.</div>}
  </main>;
}
