import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Database, RefreshCw, ShieldAlert } from 'lucide-react';
import { API, authFetch } from '@/utils/api';

const levelLabels: Record<string, string> = { normal: 'طبيعي', warning: 'تحذير', high_risk: 'خطر مرتفع', critical: 'حرج', emergency_warning: 'تحذير طوارئ', emergency_mode: 'وضع الطوارئ' };
const levelColor: Record<string, string> = { normal: 'text-emerald-400', warning: 'text-yellow-400', high_risk: 'text-orange-400', critical: 'text-red-400', emergency_warning: 'text-red-500', emergency_mode: 'text-red-600' };
function fmt(n: number) { return Number(n || 0).toLocaleString('ar'); }

export default function PostgresStorageView() {
  const [data, setData] = useState<any>(null); const [audit, setAudit] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (manual = false) => { if (manual) setLoading(true); try { const [statusRes, auditRes] = await Promise.all([authFetch(`${API}/admin/postgres-storage/status`), authFetch(`${API}/admin/postgres-storage/audit?limit=25`)]); const status = await statusRes.json(); const logs = await auditRes.json(); if (!status.success) throw new Error(status.error || 'تعذر تحميل حالة PostgreSQL'); setData(status.data); setAudit(logs.data || []); setError(''); } catch (e: any) { setError(e.message || 'تعذر الاتصال بالخادم'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(true); const timer = window.setInterval(() => load(), data?.level === 'emergency_mode' ? 5000 : 15000); return () => window.clearInterval(timer); }, [load, data?.level]);
  const progress = Math.min(100, Number(data?.usagePercent || 0)); const analysis = data?.analysis; const dominant = useMemo(() => analysis?.dominantSource, [analysis]);
  if (loading && !data) return <div className="p-8 text-secondary">جاري تحميل مراقبة PostgreSQL…</div>;
  return <div className="flex flex-col gap-6 animate-fade-in">
    <div className="flex items-center justify-between gap-4"><div><h1 className="text-heading-xl text-primary">مراقبة مساحة PostgreSQL</h1><p className="text-secondary mt-1">مراقبة مستقلة تعمل في الخلفية وتعرض آخر قياس وتحليل وإجراءات آمنة.</p></div><button onClick={() => load(true)} className="p-2.5 rounded-xl border border-[var(--border-default)] hover:bg-[var(--bg-elevated)]" title="تحديث"><RefreshCw className="w-5 h-5" /></button></div>
    {error && <div className="p-4 rounded-xl border border-red-500/30 bg-red-500/10 text-red-300">{error}</div>}
    {!data?.enabled ? <div className="p-6 rounded-2xl border border-yellow-500/30 bg-yellow-500/10 text-yellow-200">المراقبة غير مفعلة. أضف <code>POSTGRES_STORAGE_LIMIT_BYTES</code> إلى Variables الخاصة بخدمة التطبيق.</div> : <>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><div className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><p className="text-sm text-secondary">الاستخدام الحالي</p><p className={`text-4xl font-black mt-2 ${levelColor[data.level] || 'text-primary'}`}>{Number(data.usagePercent).toFixed(1)}%</p><div className="h-2 rounded-full bg-[var(--bg-elevated)] mt-4 overflow-hidden"><div className="h-full rounded-full bg-current transition-all" style={{ width: `${progress}%` }} /></div></div><div className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><p className="text-sm text-secondary">المستخدم</p><p className="text-2xl font-bold text-primary mt-2">{data.usedPretty}</p><p className="text-xs text-muted mt-1">من {data.limitPretty}</p></div><div className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><p className="text-sm text-secondary">المتبقي</p><p className="text-2xl font-bold text-primary mt-2">{data.remainingPretty}</p><p className="text-xs text-muted mt-1">قاعدة البيانات: {data.databaseName}</p></div><div className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><p className="text-sm text-secondary">مستوى الخطر</p><p className={`text-2xl font-bold mt-2 ${levelColor[data.level]}`}>{levelLabels[data.level] || data.level}</p><p className="text-xs text-muted mt-1">الحالة: {data.status}</p></div></div>
      {data.level === 'emergency_mode' && <div className="p-5 rounded-2xl border-2 border-red-500 bg-red-500/15 text-red-100 flex gap-3"><ShieldAlert className="w-7 h-7 shrink-0" /><div><p className="font-bold text-lg">Emergency Mode مفعّل</p><p className="text-sm mt-1">تم منع أي تنظيف خطِر، ويجب إيقاف العمليات غير الأساسية يدويًا أو عبر سياسة التشغيل المعتمدة مع الحفاظ على العمليات الأساسية.</p></div></div>}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><section className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><h2 className="font-bold text-primary flex items-center gap-2"><Database className="w-5 h-5 text-[var(--brand-primary)]" />مصادر الاستهلاك الأكبر</h2>{analysis ? <div className="mt-4 flex flex-col gap-3">{Object.entries(analysis.totals || {}).map(([key, value]: any) => <div key={key} className="flex items-center justify-between p-3 rounded-xl bg-[var(--bg-elevated)]"><span className={dominant?.key === key ? 'font-bold text-orange-300' : 'text-secondary'}>{key}</span><span className="font-mono text-primary">{(Number(value) / 1024 / 1024).toFixed(2)} MB</span></div>)}<p className="text-sm text-orange-300">المصدر الرئيسي: {dominant?.key || 'غير محدد'} ({(Number(dominant?.bytes || 0) / 1024 / 1024).toFixed(2)} MB)</p></div> : <p className="text-muted mt-4">يبدأ التحليل التفصيلي تلقائيًا عند 80%.</p>}</section><section className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><h2 className="font-bold text-primary flex items-center gap-2"><Activity className="w-5 h-5 text-[var(--brand-primary)]" />التوصيات والإجراء الحالي</h2><p className="text-secondary text-sm mt-4">{data.action}</p>{analysis?.recommendations?.map((item: string) => <p key={item} className="text-sm text-secondary mt-3">• {item}</p>)}</section></div>
      <section className="p-5 rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)]"><h2 className="font-bold text-primary flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-yellow-400" />سجل التدقيق</h2><div className="overflow-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-muted text-right"><th className="p-2">الوقت</th><th className="p-2">الحدث</th><th className="p-2">المستوى</th><th className="p-2">الإجراء</th><th className="p-2">النتيجة</th></tr></thead><tbody>{audit.map(log => <tr key={log.id} className="border-t border-[var(--border-default)]"><td className="p-2 text-muted">{new Date(log.created_at).toLocaleString('ar')}</td><td className="p-2 text-primary">{log.event_type}</td><td className={`p-2 ${levelColor[log.severity] || 'text-secondary'}`}>{levelLabels[log.severity] || log.severity}</td><td className="p-2 text-secondary max-w-md">{log.action}</td><td className="p-2 text-secondary flex items-center gap-1"><CheckCircle2 className="w-4 h-4 text-emerald-400" />{log.result}</td></tr>)}</tbody></table>{!audit.length && <p className="text-muted py-6 text-center">لا توجد أحداث مسجلة بعد.</p>}</div></section>
    </>}
  </div>;
}
